# Connection strings
ORACLE_CONN_STR = "AGILE_RO/agilerospt@sulvdbz22:1522/agilespt"
SOLR_URL = "http://ol-bvsolr.formfactor.com:8983/solr/DOC_test"

# SQL Queries
PARENT_QUERY = """
SELECT 
    P2P3.ITEM_NUMBER, 
    P2P3.DESCRIPTION DESCRIPTION, 
    N.DESCRIPTION SUBCLASS,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = R.RELEASE_TYPE AND PARENTID = 4539) LIFECYCLE,
    (SELECT TEXT FROM AGILE_FLEX WHERE ATTID = 2000003227 AND ID = P2P3.ID) EXTENDED_DESC,
    U.FIRST_NAME || ' ' || U.LAST_NAME CREATED_BY,
    R.RELEASE_DATE,
    R.REV_NUMBER,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST12 AND PARENTID = 2483499) DOC_PREFIX,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST13 AND PARENTID = 2483503) DOC_TYPE,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST14 AND PARENTID = 2483505) MANUFACTURING_TYPE,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST11 AND PARENTID = 2483498) AREA_WHERE_USED,
    (SELECT LISTAGG(ENTRYVALUE, ';') WITHIN GROUP (ORDER BY ENTRYVALUE) FROM AGILE.LISTENTRY 
        WHERE ENTRYID IN (
            SELECT REGEXP_SUBSTR(P2P3.MULTILIST01, '[^,]+', 1, LEVEL) FROM DUAL
            CONNECT BY REGEXP_SUBSTR(P2P3.MULTILIST01, '[^,]+', 1, LEVEL) IS NOT NULL
        ) AND PARENTID = 2483671) AS PRODUCT_ARCHITECTURE,
    (SELECT LISTAGG(ENTRYVALUE, ';') WITHIN GROUP (ORDER BY ENTRYVALUE) FROM AGILE.LISTENTRY 
        WHERE ENTRYID IN (
            SELECT REGEXP_SUBSTR(P2P3.MULTILIST02, '[^,]+', 1, LEVEL) FROM DUAL
            CONNECT BY REGEXP_SUBSTR(P2P3.MULTILIST02, '[^,]+', 1, LEVEL) IS NOT NULL
        ) AND PARENTID = 2483672) AS TECHNOLOGY,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST01 AND PARENTID = 2488109) WORK_CENTER,
    P2P3.TEXT25 LEGACY_NUMBER,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST37 AND PARENTID = 2468125) TO_LRNR_WEB,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST31 AND PARENTID = 2483502) LRNR_WEB_TRN_LEVEL,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST32 AND PARENTID = 2483526) LRNR_WEB_CHK_LIST,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST39 AND PARENTID = 2468125) TO_LITMOS,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST40 AND PARENTID = 2483502) LITMOS_TRN_LEVEL,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST41 AND PARENTID = 2483526) LITMOS_CHK_LIST,
    (SELECT LISTAGG(ENTRYVALUE, ';') WITHIN GROUP (ORDER BY ENTRYVALUE) FROM AGILE.LISTENTRY 
        WHERE ENTRYID IN (
            SELECT REGEXP_SUBSTR(P2P3.MULTILIST33, '[^,]+', 1, LEVEL) FROM DUAL
            CONNECT BY REGEXP_SUBSTR(P2P3.MULTILIST33, '[^,]+', 1, LEVEL) IS NOT NULL
        ) AND PARENTID = 2483500) AS LOCATION_WHERE_USED,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST33 AND PARENTID = 2468125) EHS_REQUIRED,
    (SELECT FIRST_NAME || ' ' || LAST_NAME FROM AGILEUSER WHERE ID = P2P3.LIST35) PROCESS_OWNER,
    (SELECT FIRST_NAME || ' ' || LAST_NAME FROM AGILEUSER WHERE ID = P2P3.LIST36) PROCESS_OWNER_MGR,
    (SELECT ENTRYVALUE FROM LISTENTRY WHERE ENTRYID = P2P3.LIST38 AND PARENTID = 2483504) REVIEW_CYCLE_TIME,
    P2P3.DATE32 REVIEW_CYCLE_DATE
FROM 
    AGILE.ITEM_P2P3 P2P3
INNER JOIN 
    AGILE.REV R ON R.ITEM = P2P3.ID AND R.RELEASE_TYPE = 974
INNER JOIN 
    AGILE.NODETABLE N ON N.ID = P2P3.SUBCLASS
INNER JOIN 
    AGILEUSER U ON U.ID = P2P3.CREATE_USER
WHERE 
    N.DESCRIPTION = 'Document'
    AND R.LATEST_FLAG = 1
    AND P2P3.DELETE_FLAG IS NULL
"""

CHILD_QUERY = """
SELECT 
    AGILE.ITEM.ITEM_NUMBER, 
    AGILE.FILES.FILENAME, 
    AGILE.FILES.FILE_TYPE, 
    AGILE.FILE_INFO.IFS_FILEPATH,
    AGILE.FILE_INFO.HFS_FILEPATH
FROM 
    AGILE.ITEM
JOIN 
    AGILE.ATTACHMENT_MAP ON AGILE.ATTACHMENT_MAP.PARENT_ID = AGILE.ITEM.ID AND AGILE.ITEM.CLASS = 9000
JOIN 
    AGILE.FILES ON AGILE.FILES.ID = AGILE.ATTACHMENT_MAP.FILE_ID
JOIN 
    AGILE.FILE_INFO ON AGILE.FILE_INFO.FILE_ID = AGILE.ATTACHMENT_MAP.FILE_ID
JOIN 
    AGILE.NODETABLE ON AGILE.NODETABLE.ID = AGILE.ITEM.SUBCLASS
WHERE 
    AGILE.NODETABLE.DESCRIPTION = 'Document'
    AND AGILE.ITEM.ID NOT IN (
        45377136, 49523767, 45377145, 
        24262189, 24262167, 24262240, 
        24262312
    )
    AND AGILE.ITEM.DELETE_FLAG IS NULL
    AND AGILE.ATTACHMENT_MAP.PARENT_ID2 = (
        SELECT CHANGE FROM REV WHERE RELEASE_DATE = (
            SELECT MAX(R.RELEASE_DATE) 
            FROM REV R, CHANGE C
            WHERE ITEM = (
                SELECT ID FROM ITEM WHERE ITEM_NUMBER = AGILE.ITEM.ITEM_NUMBER
            )
            AND C.ID = R.CHANGE
            AND C.CLASS = 6000
            AND C.DELETE_FLAG IS NULL
            AND C.RELEASE_DATE IS NOT NULL
        )
        AND ITEM = AGILE.ITEM.ID
    )
"""

CHILD_QUERY_2 = """
SELECT 
    I.ITEM_NUMBER, 
    F.FILENAME, 
    F.FILE_TYPE, 
    FI.IFS_FILEPATH, 
    FI.HFS_FILEPATH
FROM 
    ATTACHMENT_MAP AM, 
    ITEM I, 
    VERSION_FILE_MAP VFM, 
    FILES F, 
    FILE_INFO FI, 
    NODETABLE N
WHERE 
    I.ID = AM.PARENT_ID
    AND AM.VERSION_ID = VFM.VERSION_ID
    AND F.ID = VFM.FILE_ID
    AND F.ID = FI.FILE_ID
    AND AM.FILE_ID = 0
    AND N.ID = I.SUBCLASS
    AND N.DESCRIPTION = 'Document'
    AND I.DELETE_FLAG IS NULL
    AND I.ID NOT IN (
        45377136, 49523767, 45377145, 
        24262189, 24262167, 24262240, 
        24262312
    )
"""
